export const LOADING_SCREEN = "LOADING_SCREEN";
export const ERROR_CONNECTION = "ERROR_CONNECTION";
export const LOGIN_WRONG_PASSWORD = "LOGIN_WRONG_PASSWORD";
export const LOGIN_USER_NOT_EXIST = "LOGIN_USER_NOT_EXIST";
export const PUSH_APP_USER = "PUSH_APP_USER";
export const GET_QR_CODE = "GET_QR_CODE";