export const LOADING_SCREEN = "LOADING_SCREEN";
export const MODAL_OPEN = "MODAL_OPEN";
export const ERROR_CONNECTION = "ERROR_CONNECTION";
export const LOGIN_WRONG_PASSWORD = "LOGIN_WRONG_PASSWORD";
export const LOGIN_USER_NOT_EXIST = "LOGIN_USER_NOT_EXIST";
export const LOGIN_USER_EXISTED = "LOGIN_USER_EXISTED";
export const USER_NOT_LOGIN = "USER_NOT_LOGIN";
export const INACTIVE_USER = "INACTIVE_USER";

export const PUSH_APP_USER = "PUSH_APP_USER";
export const GET_QR_CODE = "GET_QR_CODE";